src/objects/Race__c.object
<CustomObject>
    <description>used to track races</description>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Race Type</label>
        <picklist>
            <picklistValues>
                <fullName>5K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>half-marathon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RaceTesting_Util.cls
@isTest
public class RaceTesting_Util {
    public static List<Race__c> newRace(Integer num) {
        
        DateTime dt = datetime.newInstance(2016, 04, 22);
        List<Race__c> races = new List<Race__c>();
        
        for (Integer i=0; i < num; i++) {
            Race__c race = new Race__c(name='New Race' + i, Type__c='5K', 
                                   Location__c='Test Location', 
                                   attended__c=false,
								    DateTime__c=dt);
            races.add(race);
        }
        
        return races;
 
    }
}