src/objects/Race__c.object
<CustomObject>
    <description>used to track races</description>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewRaceController_Test.cls
@isTest
public class NewRaceController_Test {
    //NOTE: In a real-world implementation, you shoud have more tests to cover 
    //for bulk processing and negative results and even permissions
    
	@isTest
    static void createNewRace() {
        
        Race__c raceIn = RaceTesting_Util.newRace(1)[0];
        
        Test.startTest();
        Race__c raceOut = NewRaceController.newRaceDB(raceIn);
        Test.stopTest();
        
        System.assertEquals(raceIn.Name, raceOut.Name);
    }
    
    @isTest
    static void updateRace() {
        
        Race__c raceIn = RaceTesting_Util.newRace(1)[0];
        insert raceIn;
        raceIn.Attended__c = true;
        
        Test.startTest();
        Race__c raceOut = RaceController.updateRaceDB(raceIn);
        Test.stopTest();
        
        System.assertEquals(true, raceOut.Attended__c);
    }    
    
}